import {
  AdoptionMetric,
  Agent,
  CostMetric,
  CustomerAccount,
  DataSource,
  ExecutionLog,
  FineTuneJob,
  GpuNode,
  Organization,
  QualityMetric,
  ReportItem,
  RoutingPolicy,
  SecurityEvent,
  UserRole,
  Workflow,
} from "@/lib/types";

export const roles: UserRole[] = [
  "대표/임원",
  "AI 도입 담당자",
  "IT/보안 담당자",
  "재무/구매 담당자",
  "현업 팀장",
  "일반 사용자",
  "우리 내부 운영자",
  "GPU 파트너",
  "투자자/지원사업 담당자",
];

export const dateRanges = [
  { id: "30d", label: "최근 30일" },
  { id: "quarter", label: "도입 기간 전체" },
  { id: "month", label: "2026년 5월" },
];

export const organization: Organization = {
  id: "ulsan-precision",
  name: "울산정밀부품",
  industry: "자동차 부품 제조",
  employeeCount: 126,
  aiStage: "Pilot → Business 확장 검토",
  periodStart: "2026-04-01",
  periodEnd: "2026-05-24",
  eligibleUsers: 91,
  activeUsers: 68,
  monthlyTasks: 11842,
  monthlySavedHours: 412,
  monthlySavedCost: 8730000,
  localLlmReplacementRate: 58,
  cheapEdgeShare: 31,
  qualityApprovalRate: 92.4,
  securityBlocks: 17,
  externalRoutingBlocks: 9,
  departments: [
    {
      id: "ops",
      name: "경영지원팀",
      headcount: 18,
      activeUsers: 13,
      savedHours: 61,
      monthlyCost: 169000,
      adoptionRate: 72.2,
      focusWorkflows: ["회의록 정리", "내부 문서 검색"],
    },
    {
      id: "sales",
      name: "영업팀",
      headcount: 16,
      activeUsers: 10,
      savedHours: 92,
      monthlyCost: 243000,
      adoptionRate: 62.5,
      focusWorkflows: ["견적서 초안", "고객응대 초안"],
    },
    {
      id: "quality",
      name: "품질팀",
      headcount: 14,
      activeUsers: 11,
      savedHours: 58,
      monthlyCost: 180000,
      adoptionRate: 78.6,
      focusWorkflows: ["품질 이슈 요약", "문서 검색"],
    },
    {
      id: "production",
      name: "생산기술팀",
      headcount: 21,
      activeUsers: 14,
      savedHours: 55,
      monthlyCost: 131000,
      adoptionRate: 66.7,
      focusWorkflows: ["설비 매뉴얼 검색", "회의록 정리"],
    },
    {
      id: "lab",
      name: "연구소",
      headcount: 19,
      activeUsers: 14,
      savedHours: 64,
      monthlyCost: 192000,
      adoptionRate: 73.7,
      focusWorkflows: ["연구자료 요약", "문서 검색"],
    },
    {
      id: "dev",
      name: "개발팀",
      headcount: 17,
      activeUsers: 14,
      savedHours: 44,
      monthlyCost: 227000,
      adoptionRate: 82.4,
      focusWorkflows: ["코드 테스트 초안", "문서 검색"],
    },
    {
      id: "it",
      name: "IT/보안팀",
      headcount: 11,
      activeUsers: 8,
      savedHours: 38,
      monthlyCost: 194000,
      adoptionRate: 72.7,
      focusWorkflows: ["접근권한 점검", "정책 검토"],
    },
  ],
};

export const agents: Agent[] = [
  {
    id: "doc-search",
    name: "문서검색 AI",
    departmentIds: ["ops", "quality", "lab", "dev"],
    status: "활성",
    connectedDataSourceIds: ["sharepoint", "quality-pdf", "meeting-folder", "equipment-manuals"],
    users: 42,
    monthlyRuns: 2840,
    satisfaction: 4.5,
    cost: 194000,
    securityGrade: "P1",
    recommendation: "문서 인덱스 최신화 후 무응답률을 2%p 낮출 수 있습니다.",
    approvalRate: 93.2,
    editRate: 14.1,
    rerunRate: 8.6,
    lastTunedAt: "2026-05-02",
    modelPath: "사내 RAG + 보안 SOTA API",
    summary: "부서별 문서 권한을 유지한 채 설비, 품질, 회의 자료를 검색합니다.",
    enabled: true,
    promptPolicy: ["부서 권한 없는 문서는 응답에 포함하지 않음", "민감 등급 P0는 사내 GPU에서만 후처리"],
    evaluationNotes: ["근거 문서 인용률이 91%로 양호", "신규 회의록 반영 지연 시 만족도 하락"],
    tuningHistory: ["2026-04-18 검색 랭킹 튜닝", "2026-05-02 품질 문서 어휘 보강"],
    feedback: [
      { id: "fb-1", type: "좋음", user: "김민정", comment: "설비 매뉴얼 찾는 시간이 크게 줄었습니다.", createdAt: "2026-05-18" },
      { id: "fb-2", type: "근거 부족", user: "이상훈", comment: "일부 연구자료 답변에 최신 근거가 누락되었습니다.", createdAt: "2026-05-22" },
    ],
  },
  {
    id: "meeting-ai",
    name: "회의록 AI",
    departmentIds: ["ops", "production", "sales"],
    status: "개선 필요",
    connectedDataSourceIds: ["meeting-folder"],
    users: 31,
    monthlyRuns: 2260,
    satisfaction: 4.1,
    cost: 121000,
    securityGrade: "P2",
    recommendation: "회사 양식 기반 튜닝으로 수정률을 낮출 수 있습니다.",
    approvalRate: 89.4,
    editRate: 22.9,
    rerunRate: 11.5,
    lastTunedAt: "2026-04-10",
    modelPath: "로컬 LLM + 서식 후처리",
    summary: "회의 메모를 사내 표준 양식으로 정리합니다.",
    enabled: true,
    promptPolicy: ["대외비 표시는 P1 이상으로 상향 분류", "표준 액션 아이템 형식 유지"],
    evaluationNotes: ["영업 회의록에서 문체 수정 빈도 높음", "고객명 마스킹 정책은 정상"],
    tuningHistory: ["2026-04-10 기본 요약 프롬프트 튜닝"],
    feedback: [
      { id: "fb-3", type: "수정 필요", user: "박재호", comment: "액션 아이템 주체가 종종 빠집니다.", createdAt: "2026-05-21" },
      { id: "fb-4", type: "형식 불일치", user: "윤서진", comment: "우리 회사 회의록 양식과 단락 구조가 조금 다릅니다.", createdAt: "2026-05-17" },
    ],
  },
  {
    id: "quote-ai",
    name: "견적서 AI",
    departmentIds: ["sales"],
    status: "테스트 중",
    connectedDataSourceIds: ["quote-folder", "erp-export", "customer-faq"],
    users: 18,
    monthlyRuns: 1644,
    satisfaction: 4.0,
    cost: 208000,
    securityGrade: "P0",
    recommendation: "최근 견적서 데이터를 반영한 재튜닝이 필요합니다.",
    approvalRate: 87.8,
    editRate: 26.2,
    rerunRate: 13.3,
    lastTunedAt: "2026-04-22",
    modelPath: "사내 GPU + 보안 SOTA API",
    summary: "고객 요구사항과 ERP 단가를 바탕으로 견적서 초안을 만듭니다.",
    enabled: true,
    promptPolicy: ["고객정보 포함 시 외부 라우팅 금지", "단가 표기는 ERP 최신 내역과 일치해야 함"],
    evaluationNotes: ["단가 최신성은 양호", "수정률이 높아 추가 학습 필요"],
    tuningHistory: ["2026-04-22 영업 용어 보강", "2026-05-08 단가 표 템플릿 보정"],
    feedback: [
      { id: "fb-5", type: "수정 필요", user: "최유라", comment: "옵션 항목 추천은 좋지만 문장 톤이 아직 다듬어져야 합니다.", createdAt: "2026-05-23" },
    ],
  },
  {
    id: "code-ai",
    name: "코드보조 AI",
    departmentIds: ["dev"],
    status: "활성",
    connectedDataSourceIds: ["github-repo"],
    users: 14,
    monthlyRuns: 982,
    satisfaction: 4.4,
    cost: 170000,
    securityGrade: "P0",
    recommendation: "테스트 초안 자동화를 더 넓히면 개발팀 사용 시간이 늘어납니다.",
    approvalRate: 91.7,
    editRate: 18.6,
    rerunRate: 9.1,
    lastTunedAt: "2026-05-11",
    modelPath: "사내 GPU + 코드 특화 로컬 LLM",
    summary: "사내 저장소 기준으로 테스트 초안과 코드 리뷰 메모를 만듭니다.",
    enabled: true,
    promptPolicy: ["핵심 코드와 고객 커스텀 로직은 외부 전송 금지", "오픈소스 제안 시 라이선스 경고"],
    evaluationNotes: ["테스트 초안 채택률 증가", "보안 정책 만족"],
    tuningHistory: ["2026-05-11 테스트 코드 스타일 튜닝"],
    feedback: [
      { id: "fb-6", type: "좋음", user: "홍재민", comment: "반복 테스트 작성 속도가 빨라졌습니다.", createdAt: "2026-05-20" },
    ],
  },
  {
    id: "quality-issue-ai",
    name: "품질이슈 요약 AI",
    departmentIds: ["quality", "production"],
    status: "활성",
    connectedDataSourceIds: ["quality-pdf", "erp-export"],
    users: 19,
    monthlyRuns: 1493,
    satisfaction: 4.6,
    cost: 98000,
    securityGrade: "P1",
    recommendation: "원인 분류 템플릿을 추가하면 현장 재사용성이 더 올라갑니다.",
    approvalRate: 94.1,
    editRate: 12.4,
    rerunRate: 6.1,
    lastTunedAt: "2026-05-07",
    modelPath: "사내 RAG + 로컬 LLM",
    summary: "품질 이슈와 재발 방지 액션을 요약합니다.",
    enabled: true,
    promptPolicy: ["고객사 클레임은 익명화 후 처리", "시정조치 템플릿 적용"],
    evaluationNotes: ["가장 높은 승인률", "현장 회람용 포맷 만족도 높음"],
    tuningHistory: ["2026-05-07 8D 리포트 양식 반영"],
    feedback: [
      { id: "fb-7", type: "좋음", user: "한지수", comment: "현장 공유용 요약 품질이 높습니다.", createdAt: "2026-05-18" },
    ],
  },
  {
    id: "equipment-ai",
    name: "설비매뉴얼 AI",
    departmentIds: ["production"],
    status: "활성",
    connectedDataSourceIds: ["equipment-manuals"],
    users: 22,
    monthlyRuns: 1330,
    satisfaction: 4.3,
    cost: 73000,
    securityGrade: "P1",
    recommendation: "모바일 접근성을 개선하면 현장 사용률을 더 높일 수 있습니다.",
    approvalRate: 92.9,
    editRate: 15.7,
    rerunRate: 7.4,
    lastTunedAt: "2026-04-28",
    modelPath: "사내 RAG + 로컬 LLM",
    summary: "설비 에러코드와 정비 절차를 빠르게 찾습니다.",
    enabled: true,
    promptPolicy: ["정비 로그는 부서 권한별 마스킹", "고장 분석은 근거 문서 필수"],
    evaluationNotes: ["야간조 현장 사용 증가", "모바일 UI 개선 여지"],
    tuningHistory: ["2026-04-28 설비 용어 사전 보강"],
    feedback: [
      { id: "fb-8", type: "좋음", user: "정도윤", comment: "현장 대응 시간이 줄었습니다.", createdAt: "2026-05-14" },
    ],
  },
  {
    id: "research-ai",
    name: "연구자료 AI",
    departmentIds: ["lab"],
    status: "활성",
    connectedDataSourceIds: ["sharepoint"],
    users: 12,
    monthlyRuns: 716,
    satisfaction: 4.2,
    cost: 87000,
    securityGrade: "P2",
    recommendation: "공개 논문 요약은 Cheap Edge 비중을 더 높일 수 있습니다.",
    approvalRate: 90.5,
    editRate: 17.1,
    rerunRate: 8.8,
    lastTunedAt: "2026-05-04",
    modelPath: "Cheap Edge + 근거 검수",
    summary: "공개 논문과 내부 연구 메모를 빠르게 요약합니다.",
    enabled: true,
    promptPolicy: ["대외 공개 논문만 Cheap Edge 허용", "내부 연구 메모는 P2 이상으로 분리"],
    evaluationNotes: ["공개 자료 요약 품질 안정", "내부 실험 데이터는 Secure Core 유지"],
    tuningHistory: ["2026-05-04 논문 요약 템플릿 적용"],
    feedback: [
      { id: "fb-9", type: "근거 부족", user: "서예린", comment: "표 일부가 생략되는 경우가 있습니다.", createdAt: "2026-05-19" },
    ],
  },
  {
    id: "support-ai",
    name: "고객응대 초안 AI",
    departmentIds: ["sales", "ops"],
    status: "테스트 중",
    connectedDataSourceIds: ["customer-faq", "meeting-folder"],
    users: 15,
    monthlyRuns: 577,
    satisfaction: 3.9,
    cost: 66000,
    securityGrade: "P2",
    recommendation: "FAQ와 최근 CS 사례를 추가로 반영하면 반복 질문률이 낮아집니다.",
    approvalRate: 88.6,
    editRate: 24.5,
    rerunRate: 12.1,
    lastTunedAt: "2026-04-19",
    modelPath: "로컬 LLM + Cheap Edge 혼합",
    summary: "고객 문의 답변 초안을 빠르게 만듭니다.",
    enabled: true,
    promptPolicy: ["고객사명은 마스킹 후 초안 생성", "계약 조건 답변은 영업 승인 필요"],
    evaluationNotes: ["영업팀 교육 이후 활용 가능성 높음", "수정률이 상대적으로 높음"],
    tuningHistory: ["2026-04-19 응대 톤 튜닝"],
    feedback: [
      { id: "fb-10", type: "수정 필요", user: "배수진", comment: "답변이 다소 일반적이라 실제 사례 반영이 더 필요합니다.", createdAt: "2026-05-16" },
    ],
  },
];

export const workflows: Workflow[] = [
  {
    id: "wf-meeting",
    name: "회의록 정리",
    departmentId: "ops",
    monthlyUsage: 1820,
    aiInterventionRate: 84,
    avgSavedMinutes: 2.74,
    modelRoute: "P2 → 로컬 LLM",
    securityGrade: "P2",
    approvalRate: 89.4,
    cost: 121000,
    status: "튜닝 추천",
    recommendation: "회사 양식 기반 재튜닝으로 수정률을 낮추세요.",
    beforeAvgMinutes: 5.8,
    afterAvgMinutes: 3.06,
    throughputGrowth: 31,
    monthlyVolume: 1820,
    agentIds: ["meeting-ai"],
  },
  {
    id: "wf-quote",
    name: "견적서 초안",
    departmentId: "sales",
    monthlyUsage: 1240,
    aiInterventionRate: 79,
    avgSavedMinutes: 3.68,
    modelRoute: "P0 → 사내 GPU + 보안 SOTA",
    securityGrade: "P0",
    approvalRate: 87.8,
    cost: 208000,
    status: "품질 개선 필요",
    recommendation: "최근 견적서 데이터로 재학습을 권장합니다.",
    beforeAvgMinutes: 9.4,
    afterAvgMinutes: 5.72,
    throughputGrowth: 26,
    monthlyVolume: 1240,
    agentIds: ["quote-ai"],
  },
  {
    id: "wf-search",
    name: "내부 문서 검색",
    departmentId: "ops",
    monthlyUsage: 3160,
    aiInterventionRate: 71,
    avgSavedMinutes: 1.35,
    modelRoute: "P1 → 사내 RAG",
    securityGrade: "P1",
    approvalRate: 93.2,
    cost: 194000,
    status: "효과 높음",
    recommendation: "신규 문서 동기화를 자동화하면 만족도가 더 오릅니다.",
    beforeAvgMinutes: 2.7,
    afterAvgMinutes: 1.35,
    throughputGrowth: 22,
    monthlyVolume: 3160,
    agentIds: ["doc-search"],
  },
  {
    id: "wf-quality",
    name: "품질 이슈 요약",
    departmentId: "quality",
    monthlyUsage: 1210,
    aiInterventionRate: 88,
    avgSavedMinutes: 2.88,
    modelRoute: "P1 → 사내 RAG + 로컬 LLM",
    securityGrade: "P1",
    approvalRate: 94.1,
    cost: 98000,
    status: "효과 높음",
    recommendation: "원인 분류 템플릿을 더 세분화해보세요.",
    beforeAvgMinutes: 5.76,
    afterAvgMinutes: 2.88,
    throughputGrowth: 29,
    monthlyVolume: 1210,
    agentIds: ["quality-issue-ai"],
  },
  {
    id: "wf-code",
    name: "코드 테스트 초안",
    departmentId: "dev",
    monthlyUsage: 640,
    aiInterventionRate: 76,
    avgSavedMinutes: 4.13,
    modelRoute: "P0 → 사내 GPU + 코드 특화 로컬 LLM",
    securityGrade: "P0",
    approvalRate: 91.7,
    cost: 170000,
    status: "효과 높음",
    recommendation: "테스트 커버리지 기준을 추가하면 재질문률이 더 낮아집니다.",
    beforeAvgMinutes: 8.2,
    afterAvgMinutes: 4.07,
    throughputGrowth: 18,
    monthlyVolume: 640,
    agentIds: ["code-ai"],
  },
  {
    id: "wf-support",
    name: "고객응대 초안",
    departmentId: "sales",
    monthlyUsage: 510,
    aiInterventionRate: 54,
    avgSavedMinutes: 2.31,
    modelRoute: "P2 → 로컬 LLM / Cheap Edge",
    securityGrade: "P2",
    approvalRate: 88.6,
    cost: 66000,
    status: "사용 저조",
    recommendation: "영업팀 교육과 실제 사례 데이터 보강이 필요합니다.",
    beforeAvgMinutes: 4.85,
    afterAvgMinutes: 2.54,
    throughputGrowth: 11,
    monthlyVolume: 510,
    agentIds: ["support-ai"],
  },
  {
    id: "wf-manual",
    name: "설비 매뉴얼 검색",
    departmentId: "production",
    monthlyUsage: 1330,
    aiInterventionRate: 82,
    avgSavedMinutes: 2.48,
    modelRoute: "P1 → 사내 RAG + 로컬 LLM",
    securityGrade: "P1",
    approvalRate: 92.9,
    cost: 73000,
    status: "효과 높음",
    recommendation: "모바일 사용성 개선으로 현장 활용을 더 높일 수 있습니다.",
    beforeAvgMinutes: 4.91,
    afterAvgMinutes: 2.43,
    throughputGrowth: 24,
    monthlyVolume: 1330,
    agentIds: ["equipment-ai"],
  },
  {
    id: "wf-research",
    name: "연구자료 요약",
    departmentId: "lab",
    monthlyUsage: 420,
    aiInterventionRate: 69,
    avgSavedMinutes: 3.14,
    modelRoute: "P3 → Cheap Edge + 검수",
    securityGrade: "P3",
    approvalRate: 90.5,
    cost: 87000,
    status: "비용 과다",
    recommendation: "공개 논문과 내부 자료 라우팅을 더 세분화하세요.",
    beforeAvgMinutes: 6.35,
    afterAvgMinutes: 3.21,
    throughputGrowth: 14,
    monthlyVolume: 420,
    agentIds: ["research-ai"],
  },
];

export const dataSources: DataSource[] = [
  {
    id: "sharepoint",
    name: "SharePoint 문서함",
    type: "문서 저장소",
    status: "연결됨",
    lastSync: "2026-05-24 08:10",
    documentCount: 4820,
    sensitivity: "P1",
    accessPolicy: "부서 ACL + 임원 문서 예외 규칙",
    agentIds: ["doc-search", "research-ai"],
    indexingStatus: "정상",
    hasError: false,
    summary: "표준 업무 문서와 연구 자료가 연결되어 있습니다.",
  },
  {
    id: "quality-pdf",
    name: "품질관리 매뉴얼 PDF",
    type: "PDF",
    status: "연결됨",
    lastSync: "2026-05-23 19:42",
    documentCount: 218,
    sensitivity: "P1",
    accessPolicy: "품질팀 + 생산기술팀",
    agentIds: ["doc-search", "quality-issue-ai"],
    indexingStatus: "정상",
    hasError: false,
    summary: "품질 기준서와 시정조치 사례가 연결됩니다.",
  },
  {
    id: "quote-folder",
    name: "영업 견적서 폴더",
    type: "파일 폴더",
    status: "연결됨",
    lastSync: "2026-05-24 07:55",
    documentCount: 962,
    sensitivity: "P0",
    accessPolicy: "영업팀 전용 + 고객정보 마스킹 규칙",
    agentIds: ["quote-ai"],
    indexingStatus: "정상",
    hasError: false,
    summary: "최신 견적서와 고객 요구사항 문서가 포함됩니다.",
  },
  {
    id: "github-repo",
    name: "GitHub 코드 저장소",
    type: "Git Repository",
    status: "연결됨",
    lastSync: "2026-05-24 06:40",
    documentCount: 12600,
    sensitivity: "P0",
    accessPolicy: "개발팀 + 보안 승인자",
    agentIds: ["code-ai"],
    indexingStatus: "정상",
    hasError: false,
    summary: "사내 코드와 테스트 패턴을 참조합니다.",
  },
  {
    id: "meeting-folder",
    name: "회의록 폴더",
    type: "문서 저장소",
    status: "동기화 중",
    lastSync: "2026-05-24 08:22",
    documentCount: 1524,
    sensitivity: "P2",
    accessPolicy: "작성 부서별 접근 제어",
    agentIds: ["meeting-ai", "doc-search", "support-ai"],
    indexingStatus: "재생성 필요",
    hasError: false,
    summary: "최근 회의록 구조가 변경되어 재인덱싱이 진행 중입니다.",
  },
  {
    id: "equipment-manuals",
    name: "설비 매뉴얼 문서함",
    type: "문서 저장소",
    status: "연결됨",
    lastSync: "2026-05-23 22:04",
    documentCount: 634,
    sensitivity: "P1",
    accessPolicy: "생산기술팀 + 품질팀",
    agentIds: ["equipment-ai", "doc-search"],
    indexingStatus: "정상",
    hasError: false,
    summary: "설비 정비와 에러코드 대응 절차를 보관합니다.",
  },
  {
    id: "customer-faq",
    name: "고객응대 FAQ",
    type: "FAQ",
    status: "주의 필요",
    lastSync: "2026-05-21 17:10",
    documentCount: 184,
    sensitivity: "P2",
    accessPolicy: "영업팀 + 경영지원팀",
    agentIds: ["support-ai", "quote-ai"],
    indexingStatus: "오류",
    hasError: true,
    summary: "최근 FAQ 업로드 포맷 변경으로 일부 문서 파싱 오류가 있습니다.",
  },
  {
    id: "erp-export",
    name: "ERP Export CSV",
    type: "CSV",
    status: "연결됨",
    lastSync: "2026-05-24 05:30",
    documentCount: 88,
    sensitivity: "P0",
    accessPolicy: "영업팀 + 품질팀 + 재무 승인자",
    agentIds: ["quote-ai", "quality-issue-ai"],
    indexingStatus: "정상",
    hasError: false,
    summary: "가격, 품번, 출하 이력의 최신 스냅샷이 반영됩니다.",
  },
];

export const routingPolicies: RoutingPolicy[] = [
  {
    grade: "P0",
    examples: ["계약서", "재무자료", "고객정보", "핵심 코드"],
    route: "사내 GPU / 보안 SOTA API",
    externalAllowed: false,
    description: "민감도 최고 등급. 외부 GPU 라우팅 금지.",
  },
  {
    grade: "P1",
    examples: ["내부 문서 기반 판단", "품질 기준 문서", "설비 매뉴얼"],
    route: "사내 RAG / 보안 API",
    externalAllowed: false,
    description: "사내 문서 권한과 감사 로그를 유지하며 처리.",
  },
  {
    grade: "P2",
    examples: ["마스킹 가능한 문서 정리", "회의록 초안", "고객 FAQ 정리"],
    route: "로컬 LLM",
    externalAllowed: false,
    description: "민감 요소 마스킹 후 로컬 모델 위주로 처리.",
  },
  {
    grade: "P3",
    examples: ["공개자료 요약", "초안 작성", "포맷팅"],
    route: "Cheap Edge",
    externalAllowed: true,
    description: "반복성 높은 비민감 작업에 저비용 라우팅 적용.",
  },
  {
    grade: "P4",
    examples: ["이미지 생성", "배치 작업", "실험성 작업"],
    route: "유휴 GPU / PC방 GPU Pool",
    externalAllowed: true,
    description: "민감 데이터 미포함 전제의 대규모 배치 작업.",
  },
];

export const executionLogs: ExecutionLog[] = [
  {
    id: "log-1",
    time: "2026-05-24 08:15",
    user: "사용자 A",
    task: "계약서 리스크 검토",
    sensitivityGrade: "P0",
    path: "Secure Core",
    policyResult: "외부 GPU 라우팅 차단 후 사내 RAG + 보안 SOTA 처리",
    riskLevel: "높음",
    detailSteps: [
      "계약서 업로드 요청 감지",
      "P0 문서로 분류",
      "외부 GPU 라우팅 차단",
      "사내 RAG + 보안 SOTA로 처리",
      "최종 결과 반환",
      "감사 로그 저장",
    ],
    workflowId: "wf-quote",
    agentId: "quote-ai",
    blocked: true,
  },
  {
    id: "log-2",
    time: "2026-05-24 08:04",
    user: "사용자 B",
    task: "회의록 문장 다듬기",
    sensitivityGrade: "P3",
    path: "Cheap Edge",
    policyResult: "비민감 텍스트로 판정, Cheap Edge 허용",
    riskLevel: "낮음",
    detailSteps: ["텍스트 입력 분석", "P3 분류", "Cheap Edge 모델 선택", "문체 후처리 적용", "결과 저장"],
    workflowId: "wf-meeting",
    agentId: "meeting-ai",
  },
  {
    id: "log-3",
    time: "2026-05-24 07:51",
    user: "사용자 C",
    task: "공개 논문 요약",
    sensitivityGrade: "P3",
    path: "Cheap Edge",
    policyResult: "공개 자료로 판정, 외부 유휴 GPU 허용",
    riskLevel: "낮음",
    detailSteps: ["DOI 확인", "공개 자료 판정", "Cheap Edge GPU 배정", "결과 캐시 저장"],
    workflowId: "wf-research",
    agentId: "research-ai",
  },
  {
    id: "log-4",
    time: "2026-05-24 07:33",
    user: "사용자 D",
    task: "고객정보 포함 문서 검색",
    sensitivityGrade: "P0",
    path: "Secure Core",
    policyResult: "고객식별정보 탐지, Secure Core 강제",
    riskLevel: "긴급",
    detailSteps: ["고객식별정보 탐지", "P0 상향 분류", "Cheap Edge 후보 제외", "사내 RAG 처리", "보안 감사 저장"],
    workflowId: "wf-search",
    agentId: "doc-search",
    blocked: true,
  },
  {
    id: "log-5",
    time: "2026-05-24 07:12",
    user: "사용자 E",
    task: "이미지 배치 생성",
    sensitivityGrade: "P4",
    path: "유휴 GPU Pool",
    policyResult: "실험성 배치 작업으로 P4 라우팅",
    riskLevel: "보통",
    detailSteps: ["작업 크기 확인", "P4 라우팅", "유휴 GPU Pool 배정", "완료 후 작업 종료"],
  },
  {
    id: "log-6",
    time: "2026-05-23 18:25",
    user: "사용자 F",
    task: "견적서 초안 작성",
    sensitivityGrade: "P0",
    path: "Secure Core",
    policyResult: "ERP 단가 검증 후 사내 GPU 처리",
    riskLevel: "보통",
    detailSteps: ["고객정보 포함 감지", "P0 분류", "ERP 단가 참조", "사내 GPU 처리"],
    workflowId: "wf-quote",
    agentId: "quote-ai",
  },
];

export const costMetrics: CostMetric[] = [
  { category: "보안 SOTA API", sotaOnlyCost: 920000, actualCost: 516000, savings: 404000, savingsRate: 43.9, usageShare: 38 },
  { category: "로컬 LLM", sotaOnlyCost: 410000, actualCost: 188000, savings: 222000, savingsRate: 54.1, usageShare: 24 },
  { category: "사내 GPU", sotaOnlyCost: 520000, actualCost: 332000, savings: 188000, savingsRate: 36.2, usageShare: 21 },
  { category: "Cheap Edge", sotaOnlyCost: 430000, actualCost: 120000, savings: 310000, savingsRate: 72.1, usageShare: 12 },
  { category: "문서 인덱싱", sotaOnlyCost: 120000, actualCost: 98000, savings: 22000, savingsRate: 18.3, usageShare: 5 },
];

export const securityEvents: SecurityEvent[] = [
  {
    id: "sec-1",
    time: "2026-05-24 08:15",
    type: "외부 라우팅 차단",
    user: "사용자 A",
    action: "계약서 리스크 검토",
    severity: "높음",
    sensitivity: "P0",
    result: "차단 후 Secure Core 처리",
    description: "민감 계약서가 외부 유휴 GPU 후보로 잘못 분류되기 전 정책 엔진이 차단했습니다.",
    route: "Secure Core",
    source: "Routing Policy Engine",
  },
  {
    id: "sec-2",
    time: "2026-05-24 07:33",
    type: "민감정보 탐지",
    user: "사용자 D",
    action: "고객정보 포함 문서 검색",
    severity: "긴급",
    sensitivity: "P0",
    result: "고객식별정보 마스킹 요구",
    description: "문서 검색 요청에 주민번호 유사 패턴이 포함되어 마스킹이 요구되었습니다.",
    route: "Secure Core",
    source: "DLP Scanner",
  },
  {
    id: "sec-3",
    time: "2026-05-23 15:10",
    type: "권한 없는 접근 시도",
    user: "사용자 G",
    action: "품질 문서함 접근",
    severity: "보통",
    sensitivity: "P1",
    result: "거부",
    description: "영업팀 계정으로 품질 기준서 직접 접근 시도가 감지되었습니다.",
    route: "N/A",
    source: "Access Control",
  },
  {
    id: "sec-4",
    time: "2026-05-22 17:26",
    type: "정책 위반 차단",
    user: "사용자 H",
    action: "대외비 코드 외부 분석 요청",
    severity: "긴급",
    sensitivity: "P0",
    result: "외부 전송 차단",
    description: "핵심 코드 조각이 포함된 요청이 Cheap Edge로 향하기 전에 차단되었습니다.",
    route: "Secure Core",
    source: "Policy Guard",
  },
];

export const fineTuneJobs: FineTuneJob[] = [
  {
    id: "ft-1",
    agentId: "meeting-ai",
    dataset: "회의록 표준 양식 420건",
    status: "평가 중",
    evaluationSetSize: 88,
    beforeScore: 81.4,
    afterScore: 88.9,
    costDelta: -8,
    deploymentStatus: "스테이징 배포",
    goal: "회사 양식 정렬",
    createdAt: "2026-05-22",
    rollbackAvailable: false,
  },
  {
    id: "ft-2",
    agentId: "quote-ai",
    dataset: "최근 견적서 + ERP 매핑 310건",
    status: "준비 중",
    evaluationSetSize: 64,
    beforeScore: 78.8,
    afterScore: 84.1,
    costDelta: 6,
    deploymentStatus: "대기",
    goal: "수정률 감소",
    createdAt: "2026-05-23",
    rollbackAvailable: false,
  },
  {
    id: "ft-3",
    agentId: "code-ai",
    dataset: "테스트 코드 패턴 180건",
    status: "배포 완료",
    evaluationSetSize: 42,
    beforeScore: 84.7,
    afterScore: 90.6,
    costDelta: 4,
    deploymentStatus: "프로덕션",
    goal: "테스트 초안 품질 향상",
    createdAt: "2026-05-11",
    rollbackAvailable: true,
  },
];

export const qualityMetrics: QualityMetric[] = [
  {
    agentId: "doc-search",
    approvalRate: 93.2,
    editRate: 14.1,
    reaskRate: 8.6,
    hallucinationRate: 2.3,
    citationRate: 91.0,
    evalPassRate: 92.8,
    sotaScore: 94.0,
    localScore: 89.5,
    status: "정상",
    trend: [
      { label: "4월 4주", approvalRate: 91.4, editRate: 16.1, reaskRate: 9.8, hallucinationRate: 2.9, citationRate: 88.2 },
      { label: "5월 1주", approvalRate: 92.0, editRate: 15.5, reaskRate: 9.1, hallucinationRate: 2.6, citationRate: 89.4 },
      { label: "5월 2주", approvalRate: 92.6, editRate: 14.7, reaskRate: 8.9, hallucinationRate: 2.4, citationRate: 90.1 },
      { label: "5월 3주", approvalRate: 93.2, editRate: 14.1, reaskRate: 8.6, hallucinationRate: 2.3, citationRate: 91.0 },
    ],
  },
  {
    agentId: "meeting-ai",
    approvalRate: 89.4,
    editRate: 22.9,
    reaskRate: 11.5,
    hallucinationRate: 3.7,
    citationRate: 68.0,
    evalPassRate: 85.4,
    sotaScore: 87.9,
    localScore: 83.8,
    status: "개선 필요",
    trend: [
      { label: "4월 4주", approvalRate: 87.3, editRate: 24.1, reaskRate: 12.4, hallucinationRate: 4.0, citationRate: 64.2 },
      { label: "5월 1주", approvalRate: 88.0, editRate: 23.7, reaskRate: 12.0, hallucinationRate: 3.8, citationRate: 65.5 },
      { label: "5월 2주", approvalRate: 88.8, editRate: 23.1, reaskRate: 11.8, hallucinationRate: 3.8, citationRate: 66.9 },
      { label: "5월 3주", approvalRate: 89.4, editRate: 22.9, reaskRate: 11.5, hallucinationRate: 3.7, citationRate: 68.0 },
    ],
  },
  {
    agentId: "quote-ai",
    approvalRate: 87.8,
    editRate: 26.2,
    reaskRate: 13.3,
    hallucinationRate: 4.6,
    citationRate: 82.0,
    evalPassRate: 84.6,
    sotaScore: 90.1,
    localScore: 79.4,
    status: "주의",
    trend: [
      { label: "4월 4주", approvalRate: 86.1, editRate: 27.7, reaskRate: 14.2, hallucinationRate: 5.2, citationRate: 78.0 },
      { label: "5월 1주", approvalRate: 86.8, editRate: 27.0, reaskRate: 13.9, hallucinationRate: 4.9, citationRate: 79.6 },
      { label: "5월 2주", approvalRate: 87.3, editRate: 26.6, reaskRate: 13.5, hallucinationRate: 4.7, citationRate: 80.9 },
      { label: "5월 3주", approvalRate: 87.8, editRate: 26.2, reaskRate: 13.3, hallucinationRate: 4.6, citationRate: 82.0 },
    ],
  },
  {
    agentId: "quality-issue-ai",
    approvalRate: 94.1,
    editRate: 12.4,
    reaskRate: 6.1,
    hallucinationRate: 1.9,
    citationRate: 95.0,
    evalPassRate: 94.8,
    sotaScore: 93.7,
    localScore: 91.8,
    status: "정상",
    trend: [
      { label: "4월 4주", approvalRate: 92.8, editRate: 13.7, reaskRate: 6.9, hallucinationRate: 2.1, citationRate: 92.4 },
      { label: "5월 1주", approvalRate: 93.1, editRate: 13.3, reaskRate: 6.7, hallucinationRate: 2.0, citationRate: 93.3 },
      { label: "5월 2주", approvalRate: 93.6, editRate: 12.8, reaskRate: 6.3, hallucinationRate: 2.0, citationRate: 94.2 },
      { label: "5월 3주", approvalRate: 94.1, editRate: 12.4, reaskRate: 6.1, hallucinationRate: 1.9, citationRate: 95.0 },
    ],
  },
];

export const adoptionMetrics: AdoptionMetric[] = organization.departments.map((department, index) => ({
  departmentId: department.id,
  totalUsers: Math.round(department.headcount * (department.id === "it" ? 0.9 : 1)),
  activeUsers: department.activeUsers,
  repeatUserRate: [68, 61, 72, 59, 65, 74, 70][index],
  dropOffCount: [3, 5, 2, 6, 3, 2, 2][index],
  satisfaction: [4.2, 4.0, 4.5, 4.1, 4.2, 4.4, 4.3][index],
  primaryAgent: ["문서검색 AI", "견적서 AI", "품질이슈 요약 AI", "설비매뉴얼 AI", "연구자료 AI", "코드보조 AI", "문서검색 AI"][index],
  painPoint: [
    "회의록 템플릿 일관성",
    "견적서 AI 교육 필요",
    "고객사별 용어 반영 속도",
    "모바일 접근성 부족",
    "공개 논문/내부 메모 구분 필요",
    "문서검색 AI 활용 확장 여지",
    "보안 예외 승인 흐름 개선",
  ][index],
  weeklyTrend: [
    { label: "1주", activeRate: 61 },
    { label: "2주", activeRate: 66 },
    { label: "3주", activeRate: 69 },
    { label: "4주", activeRate: Number(department.adoptionRate.toFixed(1)) },
  ],
}));

export const reports: ReportItem[] = [
  {
    id: "r-1",
    title: "경영진용 월간 ROI 리포트",
    audience: "대표/임원",
    status: "준비됨",
    updatedAt: "2026-05-24",
    summary: "이번 달 AI 처리 업무 11,842건 기준으로 412시간, 873만원의 절감 효과가 확인되었습니다.",
    highlights: ["SOTA 단독 대비 비용 46.1% 절감", "품질 승인률 92.4%", "확장 우선 대상: 영업팀 견적서 AI"],
  },
  {
    id: "r-2",
    title: "IT/보안용 감사 리포트",
    audience: "IT/보안 담당자",
    status: "준비됨",
    updatedAt: "2026-05-24",
    summary: "정책 위반 차단 17건, 외부 유휴 GPU 라우팅 차단 9건이 모두 정상 처리되었습니다.",
    highlights: ["P0 외부 라우팅 0건", "권한 없는 접근 시도 4건", "감사 로그 저장 100% 유지"],
  },
  {
    id: "r-3",
    title: "재무용 비용 리포트",
    audience: "재무/구매 담당자",
    status: "준비됨",
    updatedAt: "2026-05-24",
    summary: "실제 라우팅 비용 1,336,000원으로 SOTA 단독 예상비용 대비 1,144,000원을 절감했습니다.",
    highlights: ["Cheap Edge 처리 비율 31%", "부서별 비용 최댓값: 영업팀", "로컬 LLM 대체율 58%"],
  },
  {
    id: "r-4",
    title: "팀장용 생산성 리포트",
    audience: "현업 팀장",
    status: "준비됨",
    updatedAt: "2026-05-24",
    summary: "업무별 절감 효과가 가장 큰 항목은 회의록 정리, 견적서 초안, 내부 문서 검색입니다.",
    highlights: ["회의록 정리 83시간 절감", "견적서 초안 76시간 절감", "품질 이슈 요약 승인률 94.1%"],
  },
  {
    id: "r-5",
    title: "현업용 사용 사례 리포트",
    audience: "일반 사용자",
    status: "준비됨",
    updatedAt: "2026-05-24",
    summary: "사내 데이터를 넣으면 업무별 AI Agent가 자동 생성되고, 권한 범위 내 문서만 검색됩니다.",
    highlights: ["추천 Agent 3종", "팀별 베스트 프롬프트", "교육 대상 사용자 목록"],
  },
  {
    id: "r-6",
    title: "우리 내부용 고객 상태 리포트",
    audience: "우리 내부 운영자",
    status: "준비됨",
    updatedAt: "2026-05-24",
    summary: "울산정밀부품은 Pilot 종료 전 확장 가능성이 높고, 견적서/회의록 튜닝 수요가 큽니다.",
    highlights: ["확장 가능 업무 4건", "이탈 위험 낮음", "추가 업셀 후보: 품질팀 전사 확산"],
  },
];

export const gpuNodes: GpuNode[] = [
  {
    id: "gpu-1",
    partnerName: "동대구 e스포츠 PC방",
    label: "RTX 4080 Pool A",
    totalGpu: 12,
    activeGpu: 7,
    todayRevenue: 186000,
    monthlyPayoutForecast: 4120000,
    hours: 84,
    avgTemp: 67,
    interruptions: 2,
    priorityReturns: 5,
    status: "정상",
    maxTemp: 75,
    maxUtilization: 68,
    schedule: "22:00-08:00",
    autoInterrupt: true,
  },
  {
    id: "gpu-2",
    partnerName: "울산 테크 PC존",
    label: "RTX 4070 Cluster B",
    totalGpu: 9,
    activeGpu: 4,
    todayRevenue: 124000,
    monthlyPayoutForecast: 2980000,
    hours: 61,
    avgTemp: 64,
    interruptions: 1,
    priorityReturns: 3,
    status: "정상",
    maxTemp: 74,
    maxUtilization: 63,
    schedule: "23:30-09:00",
    autoInterrupt: true,
  },
  {
    id: "gpu-3",
    partnerName: "수성구 하이엔드 PC클럽",
    label: "RTX 4090 Test Lane",
    totalGpu: 6,
    activeGpu: 5,
    todayRevenue: 212000,
    monthlyPayoutForecast: 5080000,
    hours: 92,
    avgTemp: 71,
    interruptions: 3,
    priorityReturns: 6,
    status: "주의",
    maxTemp: 73,
    maxUtilization: 72,
    schedule: "01:00-10:00",
    autoInterrupt: true,
  },
];

export const customerAccounts: CustomerAccount[] = [
  {
    id: "c-1",
    name: "울산정밀부품",
    mrr: 5400000,
    activeUsers: 68,
    usageGrowth: 18,
    costMargin: 44,
    qualityComplaints: 6,
    securityAlerts: 2,
    tuningNeed: "견적서 AI, 회의록 AI",
    renewalRisk: "확장 가능",
    expansionOpportunity: "영업팀 전사 확산, 품질팀 추가 Agent",
    nextAction: "Pilot 결과 리뷰 후 Business 플랜 제안",
  },
  {
    id: "c-2",
    name: "대구메디텍",
    mrr: 4300000,
    activeUsers: 53,
    usageGrowth: 11,
    costMargin: 39,
    qualityComplaints: 3,
    securityAlerts: 1,
    tuningNeed: "의료 문서검색 AI",
    renewalRisk: "정상",
    expansionOpportunity: "CS 자동화",
    nextAction: "도입 교육 리마인드",
  },
  {
    id: "c-3",
    name: "성수커머스랩",
    mrr: 3200000,
    activeUsers: 41,
    usageGrowth: 4,
    costMargin: 28,
    qualityComplaints: 11,
    securityAlerts: 0,
    tuningNeed: "상품설명 초안 AI",
    renewalRisk: "품질 이슈",
    expansionOpportunity: "상품 QA 워크플로우",
    nextAction: "품질 개선 태스크포스 제안",
  },
  {
    id: "c-4",
    name: "포항소재연구소",
    mrr: 6100000,
    activeUsers: 72,
    usageGrowth: 22,
    costMargin: 47,
    qualityComplaints: 2,
    securityAlerts: 1,
    tuningNeed: "연구자료 AI",
    renewalRisk: "정상",
    expansionOpportunity: "논문 요약 템플릿 판매",
    nextAction: "공동 과제형 리포트 제안",
  },
  {
    id: "c-5",
    name: "부산물류파트너스",
    mrr: 2800000,
    activeUsers: 29,
    usageGrowth: -3,
    costMargin: 21,
    qualityComplaints: 8,
    securityAlerts: 3,
    tuningNeed: "배차 문서 AI",
    renewalRisk: "이탈 위험",
    expansionOpportunity: "운송 리포트 자동화",
    nextAction: "긴급 CS 및 보안 점검",
  },
];

export const dashboardTimeseries = {
  processingTime: [
    { label: "도입 전", baseline: 8.6, current: 8.6 },
    { label: "4월 1주", baseline: 8.4, current: 6.7 },
    { label: "4월 3주", baseline: 8.3, current: 6.1 },
    { label: "5월 1주", baseline: 8.2, current: 5.4 },
    { label: "5월 3주", baseline: 8.2, current: 4.9 },
  ],
  costComparison: [
    { label: "1주차", sota: 590000, actual: 336000 },
    { label: "2주차", sota: 612000, actual: 352000 },
    { label: "3주차", sota: 638000, actual: 343000 },
    { label: "4주차", sota: 640000, actual: 305000 },
  ],
  adoptionTrend: [
    { label: "4월 4주", activeRate: 58.2, target: 65 },
    { label: "5월 1주", activeRate: 66.4, target: 68 },
    { label: "5월 2주", activeRate: 71.2, target: 72 },
    { label: "5월 3주", activeRate: 74.7, target: 75 },
  ],
};

export const roleHighlights: Record<
  UserRole,
  { headline: string; focusMetric: string; actions: string[] }
> = {
  "대표/임원": {
    headline: "Pilot 기준 ROI가 충분히 입증되어 영업팀과 품질팀 확장 검토가 가능한 상태입니다.",
    focusMetric: "순효과와 확장 우선순위",
    actions: [
      "ROI 기준으로 견적서 AI와 품질이슈 요약 AI를 우선 확장하세요.",
      "회의록 AI 튜닝을 완료한 뒤 전사 공유 표준으로 올리세요.",
      "고객 정보 포함 업무는 계속 Secure Core에 고정하세요.",
    ],
  },
  "AI 도입 담당자": {
    headline: "사용률과 품질을 동시에 끌어올릴 수 있는 다음 액션이 정리되어 있습니다.",
    focusMetric: "도입률과 업무 확장성",
    actions: [
      "영업팀 대상 견적서 AI 온보딩 세션을 예약하세요.",
      "문서검색 AI의 신규 데이터 동기화를 자동화하세요.",
      "재튜닝 추천 Agent 2종을 이번 달 안에 실행하세요.",
    ],
  },
  "IT/보안 담당자": {
    headline: "정책 엔진이 정상 동작 중이며 P0 외부 라우팅은 0건입니다.",
    focusMetric: "정책 위반 차단과 감사 로그",
    actions: [
      "외부 라우팅 차단 9건 상세 로그를 월간 감사 리포트에 포함하세요.",
      "FAQ 데이터 소스 파싱 오류를 수정해 민감도 재분류를 다시 실행하세요.",
      "권한 없는 접근 시도 패턴을 부서 교육 자료로 공유하세요.",
    ],
  },
  "재무/구매 담당자": {
    headline: "실제 라우팅 비용은 SOTA 단독 대비 46.1% 낮으며 구독료 대비 순효과가 양호합니다.",
    focusMetric: "비용 절감과 부서별 배분",
    actions: [
      "Cheap Edge 처리 비율을 P3 업무 중심으로 35%까지 확대 검토하세요.",
      "영업팀 견적서 AI의 품질 개선 후 추가 라이선스 구매를 판단하세요.",
      "사내 GPU 사용량이 높은 업무는 예약 슬롯 정책을 조정하세요.",
    ],
  },
  "현업 팀장": {
    headline: "팀별 절감시간과 수정률을 같이 봐야 현업 반발 없이 확산됩니다.",
    focusMetric: "팀 생산성과 실사용성",
    actions: [
      "회의록 AI 수정 패턴을 수집해 팀 표준 템플릿을 정리하세요.",
      "생산기술팀은 설비매뉴얼 AI 모바일 접근성을 우선 개선하세요.",
      "품질팀 베스트 프롬프트를 팀 단위로 공유하세요.",
    ],
  },
  "일반 사용자": {
    headline: "권한 범위 안에서 바로 쓸 수 있는 Agent와 추천 워크플로우가 준비되어 있습니다.",
    focusMetric: "바로 사용 가능한 Agent",
    actions: [
      "문서검색 AI로 최근 회의록과 품질 문서를 먼저 찾아보세요.",
      "견적서 초안은 AI가 먼저 만들고 최종 단가만 직접 검토하세요.",
      "민감 데이터는 외부 유휴 GPU로 라우팅되지 않습니다.",
    ],
  },
  "우리 내부 운영자": {
    headline: "울산정밀부품은 확장 가능성이 높은 계정이며 튜닝 레시피 축적 가치가 큽니다.",
    focusMetric: "확장 기회와 계정 건강도",
    actions: [
      "회의록/견적서 튜닝 결과를 재사용 가능한 템플릿으로 정리하세요.",
      "Pilot 종료 전 ROI 리포트와 보안 리포트를 함께 제시하세요.",
      "영업팀 교육 패키지를 업셀 항목으로 제안하세요.",
    ],
  },
  "GPU 파트너": {
    headline: "Cheap Edge 배치 작업은 수익원이지만 손님 이용이 항상 우선입니다.",
    focusMetric: "가동률과 정산 안정성",
    actions: [
      "최대 온도와 사용률 제한을 보수적으로 유지하세요.",
      "자동 중단 토글을 항상 활성화하세요.",
      "민감 데이터는 처리하지 않습니다.",
    ],
  },
  "투자자/지원사업 담당자": {
    headline: "고객별 구축이 아니라 템플릿과 튜닝 레시피가 축적되는 플랫폼 구조가 보입니다.",
    focusMetric: "반복 매출과 플랫폼 확장성",
    actions: [
      "고객군별 템플릿 누적 수와 재사용률을 강조하세요.",
      "Cheap Edge와 Secure Core의 하이브리드 구조를 차별점으로 제시하세요.",
      "Demo aggregated data 배지를 유지해 익명화 원칙을 분명히 하세요.",
    ],
  },
};

export const routingSimulationOptions = [
  {
    task: "계약서 리스크 검토",
    grade: "P0",
    route: "Secure Core",
    result: "외부 GPU 라우팅 금지, 사내 GPU / 보안 SOTA 처리",
  },
  {
    task: "회의록 문장 다듬기",
    grade: "P3",
    route: "Cheap Edge",
    result: "비민감 텍스트 기준으로 Cheap Edge 가능",
  },
  {
    task: "공개 논문 요약",
    grade: "P3",
    route: "Cheap Edge",
    result: "공개 자료로 분류되어 Cheap Edge 허용",
  },
  {
    task: "견적서 초안 작성",
    grade: "P0",
    route: "Secure Core",
    result: "고객정보 포함 가능성으로 Secure Core 강제",
  },
  {
    task: "고객정보 포함 문서 검색",
    grade: "P0",
    route: "Secure Core",
    result: "외부 GPU 라우팅 금지, 사내 RAG 처리",
  },
  {
    task: "이미지 배치 생성",
    grade: "P4",
    route: "유휴 GPU Pool",
    result: "민감 데이터 미포함 전제로 유휴 GPU Pool 허용",
  },
];
